# Generated by Django 5.0.3 on 2024-03-22 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выпуска'),
        ),
    ]
