# Generated by Django 5.0.3 on 2024-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(default=2024, verbose_name='Дата выпуска'),
        ),
    ]
